### ISSUE TITLE
有一个需求，想请教一下。

### ISSUE THREAD

**Issue by cz848** [cantonjs/create-wxapp-page#1]
我想实现在已有的目录下创建新页面，发现此工具无法满足要求。尝试改造遇到困难，关键问题在于我不知道如何实现如果输入目录就使用输入的目录名，不输入就默认使用上面输入的页面名称（结合现有功能）。虽然用一些极端手段可以实现，但是总觉得不完美。所以能否请作者加一下这个功能？

**Comment by jaceechan** [comment]
你好，请问可以再详细点描述你的需求么？

**Comment by cz848** [comment]
感谢回复。
我的需求是想多加一条选项，可以填写生成的目录（就是在pages下面的已有的某个目录）。有时候不想因为一个简单的页面再去多生成一条目录，而且某些页面属于同一类，就想放在同一个目录下。

**Comment by jaceechan** [comment]
你好，感谢你提的意见，本工具原本目的是为了减少开发微信小程序时新增页面过于繁琐的问题，你提出的问题，

你的需求时我理解是需要在当前开发页面中新增一个页面，例如正在开发pages/home下面的文件，你还需要在home文件夹下新建文件或目录，如果是这种需求的话可以通过使用编辑器的一些插件快速实现，例如sublime的[AdvancedNewFile](https://github.com/skuroda/Sublime-AdvancedNewFile)

**Comment by cz848** [comment]
AdvancedNewFile应该不能像本工具一样生成一套小程序的(wxml,js,json,wxss)模板吧，只是简化了在多层目录下创建一个文件的步骤。而且并不是每个人都用sublime，所以还是期望能用一套工具解决。

**Comment by jaceechan** [comment]
好想有点理解错你的需求了，能通过举例子说明一下么，目录结构是怎样的，想输入什么命令，生成怎样的文件，谢谢

**Comment by cz848** [comment]
只是想多加一个生成的子目录的填写项，如果不填写，就默认与name相同。我截图吧。

**Comment by Cap32** [comment]
`inquirer` question [options](https://github.com/SBoudrias/Inquirer.js/blob/master/README.md#questions) 中的 `default`支持使用函数，第一个参数为 answers session，这应该是你想要的。

我先 close 这个 issue，PR welcome. 有疑问可以 reopen 这个 issue

**Comment by cz848** [comment]
不错，我要的就是这个效果。感谢。
