### ISSUE TITLE
是否可以支持自定义样式格式？

### ISSUE THREAD

**Issue by imyelo** [cantonjs/create-wxapp-page#3]
我在用 postcss，后缀是 ``pcss`` 或者 ``css``，也有 stylus 的项目是用 ``styl``。如果可以自定义样式的后缀名就更好了 :smile:

**Comment by Cap32** [comment]
PR welcome 😜

**Comment by Cap32** [comment]
Closed by https://github.com/cantonjs/create-wxapp-page/commit/06b34965058db264dbc1b9d1cebb855953948b55
